version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MONGO_URL=mongodb://mongodb:27017/ia-measure
    volumes:
      - .:/home/node
    working_dir: /home/node/dist  # Alterado para dist
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
