services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MONGO_URL=mongodb://mongodb:27017/ia-measure
    depends_on:
      - mongodb
    networks:
      - node-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - node-network

volumes:
  mongodb_data:


networks:
  node-network:
    driver: bridge
